### PR TITLE
Change the private information

### PR DESCRIPTION
**Pull request by JingjingShii**

### CODE REVIEW

**Review by gjwgit — COMMENTED** [review]
Please keep README.md in docs - else readthedocs will fail to build.

private_key() should be exported from mlhub.pkg - aiming for mlhub.pkg to contain the tools required for a package maintainer. I think we also need to move get_cmd_cwd() into mlhub.pkg.

Use sys.exit("Message") to exit on error and display a message instead of print()/quit(). quit() does not set the status code from the program hence can not tell if an error occured when running the program frmo the command line.

**Review by gjwgit — COMMENTED** [review]
The re**uq**est_priv_info() should probably be re**qu**est_priv_info() 

Is get_private still required for each command now - it is still being imported.

**Comment by JingjingShii** [comment]
> The re**uq**est_priv_info() should probably be re**qu**est_priv_info()
>
> Is get_private still required for each command now - it is still being imported.

This typo has been fixed in other package, I'll fix shortly.
My plan was to remove this import after finishing azface.

**Comment by gjwgit** [comment]
I was reviewing too soon :-) - thanks for the updates.

**Review by gjwgit — APPROVED** [review]
All looks good - thanks.

**Pull request merged**
